### ISSUE TITLE
Provide SEG-Y I/O functions

### ISSUE THREAD

**Issue by ar4** [ar4/deepwave#11]
There are excellent Python SEG-Y I/O packages, such as [segyio](https://github.com/Statoil/segyio). These tend to provide more flexibility than is needed for the pre-stack cases that Deepwave targets. It may thus be convenient for users if there were wrappers around `segyio` (or another package) to simplify pre-stack usage. It should be able to save forward modeled receiver amplitudes as a new SEG-Y, and read the true receiver data for use in backpropagation (potentially split over multiple files). Being able to read navigation files (P1 format, etc.) would also be great, as would the ability to operate when distributed across a cluster and to integrate with PyTorch DataLoaders.

**Comment by erellaz** [comment]
Thanks again for sharing Deepwave with the community. It is a fantastic package. Thanks also for your support.

Here is a contribution: a SEGY wrapper for Deepwave (or any other python forward modeling package). It includes a full example going from a classic benchmark SEGY velocity model (the BP tooth model) to SEGY shots generated by Deepwave and usable by any seismic package.
The example is 2D, but the package will work in 3D (with a few judicious reshape). 
It also uses Obspy (built on SEGYIO) which is more convenient (or higher level) than SEGYIO alone to write actual SEGYs from scratch. 

https://github.com/erellaz/SEGY_Wrapper/blob/main/README.md

**Comment by ar4** [comment]
Nice work! I have always found writing data to SEG-Y from Python to be
troublesome, so this will be useful. Thank you. I am also very pleased to
hear that you have found Deepwave to be useful. The dispersion that you saw
is a bit concerning. I suspect that it is due to using quite a low order
finite difference approximation. I used a low one to make the process
faster, especially for FWI, but it's probably too low for some situations.

I would like to add a reference to your repository to the Deepwave README.
How does this sound:

@erellaz has created [a nice tool](https://github.com/erellaz/SEGY_Wrapper)
to make loading and saving SEG-Y files easier, and a demonstration of using
Deepwave for forward modeling with a realistic 2D model.

**Comment by erellaz** [comment]
Awesome, thanks. Feel free to use as you see fit. 
I will keep working on the wrapper in the next few days to populate key headers of the Segy from the Deepwave geometry (at least shot number, receiver number, shot and receiver X and Y and offsets), and add a few details (custom EBCDIC from files).
