### ISSUE TITLE
Is that possible to swith the forward and backward function in BornPropagator.

### ISSUE THREAD

**Issue by bbsun** [ar4/deepwave#19]
It is nice to see the implementation of Born operator in deepwave. The born approximation is a linear operator. Is that possible to have another function ( Propagator) which considers the RTM imaging as forward operator while the Born modeling as backward operator. Or there exists a simple way to achieve this?

**Comment by ar4** [comment]
I'm glad that you like the new Born propagator. Thank you for your feature suggestion of another forward operator. Do you have references that explain how the operator you propose works? Can you tell me what the advantages of implementing it would be?
