### ISSUE TITLE
How to use cpu save the temp wavefiled while using GPU for computing. 

### ISSUE THREAD

**Issue by bbsun** [ar4/deepwave#21]
deepwave is nice, but it has an issue that, because normally GPU has small memory, thus it would be nice to only use GPU for computation, but the source wavefield which is large and used in computing the gradient is saved in CPU. Is that possible to modify the code to do so.

**Comment by ar4** [comment]
I am delighted to hear that you like Deepwave, and hope that you find it
useful. You are indeed right that storing the source wavefield on the GPU
for all timesteps needed in the imaging condition limits its usage to small
models. Unfortunately I will not have time to implement the option to store
the wavefield in CPU memory or on disk soon, but you are very welcome to
implement it and submit it as a pull request if you would like to
contribute this useful feature.

**Comment by Tortoise17** [comment]
@ Alan / (@ar4)
Indeed this library / tool is wonderful . I am thinking to use it for advanced research and development. I would like to inform you about my upcoming.
