### ISSUE TITLE
Getting error : Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ADharaUTEXAS123007** [ar4/deepwave#22]
Dear Sir,

I installed deepwave and other modules successfully and then tried running the first wave propagation example. 

When I try to do this line:
receiver_amplitudes = prop(source_amplitudes, x_s, x_r, dt)

I get the following error : Segmentation fault (core dumped)

Thanks and Regards,
Arnab

**Comment by ar4** [comment]
Dear Arnab,

I am sorry to hear that you are having trouble with Deepwave. Thank you for
letting me know. Unfortunately I have not yet been able to reproduce the
error that you encountered - I just tried running the example on a CPU and
a GPU using a clean install of Deepwave and both completed successfully. I
wonder if this might be related to Issue #20 (
https://github.com/ar4/deepwave/issues/20). I have only tested the package
on Linux systems, but it seems from that Issue that people using other
operating systems (or compilers other than GCC) might experience trouble.
Removing the "restrict" keyword, as mentioned in that issue, might solve
it. Another option is to use Google Colaboratory (colab.research.google.com)
instead of running on your own computer, as I know that it works there.

-Alan

**Comment by ar4** [comment]
Dear Arnab,

I have modified the code to change `__restrict__` to `__restrict`. The latter is apparently supported by more compilers, so it might resolve your problem. This change is incorporated in release v0.0.7. To update to this version, run `pip install -U deepwave`.

-Alan

**Comment by wslhhh1994** [comment]
> Dear Arnab,
> 
> I have modified the code to change `__restrict__` to `__restrict`. The latter is apparently supported by more compilers, so it might resolve your problem. This change is incorporated in release v0.0.7. To update to this version, run `pip install -U deepwave`.
> 
> -Alan
Thanks for your code sir.
I also get this error on my machine, which has the environmen of pytorch1.0 ,cuda9.0, and gcc 4.9.2 , and I changed the __restrict__, but it still didn't work  and have the same error of  "Segmentation fault (core dumped) " .
In addition, l had read your essay"Seismic Full_waveform iversion using deep learning tools and techniques",the  idea in this essay is very advanced. In this essay, you said your implementation is on Tensorflow.  Can you upload the code of Tensorflow  version? Thanks very much!!!

**Comment by wslhhh1994** [comment]
Thanks for your code sir.
I also get this error on my machine, which has the environmen of pytorch1.0 ,cuda9.0, and gcc 4.9.2 , and I changed the restrict, but it still didn't work and have the same error of "Segmentation fault (core dumped) " .
In addition, l had read your essay"Seismic Full_waveform iversion using deep learning tools and techniques",the idea in this essay is very advanced. In this essay, you said your implementation is on Tensorflow. Can you upload the code of Tensorflow version? Thanks very much!!!

**Comment by wslhhh1994** [comment]
Dear Alan,
    I'm appreciated that you can reply so fast.  I'll try it on   Google Colaboratory.   
    By the way ,I found it works when change the device = torch.device('cuda:0')   to  device = torch.device('cpu') .Maybe there are something wrong in my GPU (I guess ,hah)
     Thanks again!

**Comment by ar4** [comment]
I'm glad that you got it to work locally on your CPU, but it would be nice to get it working on your GPU as well. Does PyTorch normally work on your GPU? Did the Deepwave package seem to install without error? As you may know, you can also use a GPU for free on Google Colaboratory, so hopefully that will work for you if you cannot get it to work on your own computer.

**Comment by wslhhh1994** [comment]
I think pytorch does work on my GPU. When I run simple examples such as a = torch.ones(1,1)  print(a.cuda()) and torch.cuda.is_available(),  there is no error.
And I will continue to check my environment and code. If  I find which makes this problem, I would comment here.
Thanks for your generous help again.
