### ISSUE TITLE
About the PML 

### ISSUE THREAD

**Issue by guoketing** [ar4/deepwave#31]
Dear Alan,

I'm sorry to disturb you again. After reading  the source code of finite difference wave equation discretization. I have some questions about PML, I don't know why you set the auxiliary wavefield like this. I wonder the paper to support the auxiliary wavefield and the PML. Thank you very much!! 

-Keting

**Comment by ar4** [comment]
Dear Keting,

I am glad that you were able to find and understand the code for the
propagators. I believe I used the PML implementation that I found in PySIT.
I remember that at the time when I implemented it I also struggled to
understand where this came from, but it seemed to work and I think I
remember that it was simpler than other published PML methods that I found,
so I decided to use it. I have just verified that my 2D implementation does
indeed seem to be equivalent to the 2D implementation in PySIT:
https://github.com/pysit/pysit/blob/master/pysit/solvers/constant_density_acoustic/time/scalar/constant_density_acoustic_time_scalar_2D_4.h
. Do you think that a different formulation might be better?

-Alan

**Comment by guoketing** [comment]
Dear Alan,

Thank you for your reply, I would see the PML method in the PySIT, and I will try to implement other PML methods in published papers, if they have better results compare to this method. I'll connect to you to improve the deepwave.

-Keing

**Comment by ar4** [comment]
The PML that was used in the previous versions of Deepwave was, as I mentioned, based on the one in PySIT. The author of PySIT discusses the origin of this PML here: https://github.com/pysit/pysit/issues/34

I changed the PML in v0.0.10 of Deepwave to use the one proposed by Pasalic and McGarry, which I find to work better at near-grazing incidence (which is especially important if you do not have a free surface).
