### ISSUE TITLE
Some problem reinstall deepwave

### ISSUE THREAD

**Issue by guoketing** [ar4/deepwave#34]
Dear Alan,

I have coded the elastic case code of the deepwave. But when I test my code, I meet one problem. I try to reinstall the deepwave to compile my cpp and cu codes to pyd file. There is one error I can't solve the detail is as follow:
C:\Users\Keting\Downloads\deepwave\deepwave-master>python setup.py install
Warning: 'classifiers' should be a list, got type 'tuple'
running install
running bdist_egg
running egg_info
writing deepwave.egg-info\PKG-INFO
writing dependency_links to deepwave.egg-info\dependency_links.txt
writing requirements to deepwave.egg-info\requires.txt
writing top-level names to deepwave.egg-info\top_level.txt
reading manifest file 'deepwave.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'deepwave.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
D:\software\anaconda\lib\site-packages\torch\utils\cpp_extension.py:287: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building 'scalar1d_cpu_iso_4_float' extension
Emitting ninja build file C:\Users\Keting\Downloads\deepwave\deepwave-master\build\temp.win-amd64-3.8\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.10.2
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:D:\software\anaconda\lib\site-packages\torch\lib /LIBPATH:D:\software\anaconda\libs /LIBPATH:D:\software\anaconda\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.2\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64" c10.lib torch.lib torch_cpu.lib torch_python.lib /EXPORT:PyInit_scalar1d_cpu_iso_4_float C:\Users\Keting\Downloads\deepwave\deepwave-master\build\temp.win-amd64-3.8\Release\deepwave\scalar\scalar_cpu.obj C:\Users\Keting\Downloads\deepwave\deepwave-master\build\temp.win-amd64-3.8\Release\deepwave\scalar\scalar.obj C:\Users\Keting\Downloads\deepwave\deepwave-master\build\temp.win-amd64-3.8\Release\deepwave\scalar\scalar_wrapper.obj /OUT:build\lib.win-amd64-3.8\scalar1d_cpu_iso_4_float.cp38-win_amd64.pyd /IMPLIB:C:\Users\Keting\Downloads\deepwave\deepwave-master\build\temp.win-amd64-3.8\Release\deepwave\scalar\scalar1d_cpu_iso_4_float.cp38-win_amd64.lib -fopenmp
LINK : warning LNK4044: unrecognized option“/fopenmp”；ignored
LINK : error LNK2001: unresolved external symbol PyInit_scalar1d_cpu_iso_4_float
C:\Users\Keting\Downloads\deepwave\deepwave-master\build\temp.win-amd64-3.8\Release\deepwave\scalar\scalar1d_cpu_iso_4_float.cp38-win_amd64.lib : fatal error LNK1120: 1 unresolved external command
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\link.exe' failed with exit status 1120

This problem bothered me all day, Do you know how to solve it?

Keting.

**Comment by ar4** [comment]
Dear Keting,

If you would like to share your code, I can look at it to try to determine
the problem. Perhaps you could upload it to a GitHub repository?

-Alan

**Comment by guoketing** [comment]
Dear Alan,

I'm sorry to reply you late. I haven't finished all the code yet, When I code the forward function of elastic case. I'll try to test it and share the code to you. It will cost a few days.

Keting

**Comment by ar4** [comment]
Dear Keting,

That's quite alright. Thank you for the update. I will look forward to
seeing it whenever it is ready.

-Alan

**Comment by guoketing** [comment]
Dear Alan,

I have code the forward function of elastic case using cpu, but only the 2d case is achieved. I haven't test it, because I am not familiar with cuda code. I don't know how to increase a for loop in the cu file.  I find you achieve it using 
"  const ptrdiff_t shot = blockIdx.z * blockDim.z + threadIdx.z;
  const ptrdiff_t z = blockIdx.y * blockDim.y + threadIdx.y + ZPAD;
  const ptrdiff_t y = blockIdx.x * blockDim.x + threadIdx.x + YPAD;
"
I can't understand it, I wonder whether it can work if I copy the above code again to achieve the same function. If it doesn't work, how do I solve it? 
The relative codes I will send to you by email. The pml condition I use in elastic case is CFS-PML. The relative codes I will send to you by email,  thank you!!!

Keting

**Comment by guoketing** [comment]
Dear Alan,


They are the codes of elastic case, I only achieve the forward function in 2d case. I want to know if they do work. If they are right, I'll achieve the rest code. Thank you!!


Keting&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ar4/deepwave"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月28日(星期二) 凌晨4:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ar4/deepwave] Some problem reinstall deepwave (#34)





 Dear Keting,
 
 That's quite alright. Thank you for the update. I will look forward to
 seeing it whenever it is ready.
 
 -Alan
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ar4** [comment]
Dear Keting,

You can just make a CPU-only version first, if you want, but if you
wish to learn CUDA in order to make a GPU version too, then the
programming guide explains it:
https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html . If
you want to send your code by email, then my address is alan at
ausargeo dot com.

**Comment by guoketing** [comment]
Dear Alan.


I’m sorry the codes ware not sent to you yesterday, I put the codes in the email file, it seem that you didn't accept them.  I try to  upload the file to the deepwave. But the uploads are disabled, 
![image](https://user-images.githubusercontent.com/42222614/135378081-45104330-dbe2-481b-b291-363ca8eab6c8.png)
The codes have been sent to you by email.  If you don't accept them, I'll send to you again.

Keting

**Comment by ar4** [comment]
Dear Keting,

It must have been rejected by a spam filter the first time, but I have
received the code now and will work on it today.
