### ISSUE TITLE
Installation failed on Linux HPC nodes via Slurm and pip

### ISSUE THREAD

**Issue by izzatum** [ar4/deepwave#37]
Hi Alan,

I hope to find you well and in the best of health.

I'm experiencing difficulties in installing deepwave on our HPC nodes which operates on Linux. I tried to install via Slurm and normal pip, unfortunately, no success. Could you assist me with this? I pasted the error below.

Thanks!

Building wheels for collected packages: deepwave
  Building wheel for deepwave (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /ibex/scratch/izzatum/pytorch_project/env/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4dd_7iq8/deepwave_8660e702ae784fbdb012b4e28101f5f6/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4dd_7iq8/deepwave_8660e702ae784fbdb012b4e28101f5f6/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ugjf6an2
       cwd: /tmp/pip-install-4dd_7iq8/deepwave_8660e702ae784fbdb012b4e28101f5f6/
  Complete output (70 lines):
  Warning: 'classifiers' should be a list, got type 'tuple'
  running bdist_wheel
  /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/utils/cpp_extension.py:381: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
    warnings.warn(msg.format('we could not find ninja.'))
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.9
  creating build/lib.linux-x86_64-3.9/deepwave
  copying deepwave/__init__.py -> build/lib.linux-x86_64-3.9/deepwave
  copying deepwave/utils.py -> build/lib.linux-x86_64-3.9/deepwave
  copying deepwave/wavelets.py -> build/lib.linux-x86_64-3.9/deepwave
  creating build/lib.linux-x86_64-3.9/deepwave/base
  copying deepwave/base/__init__.py -> build/lib.linux-x86_64-3.9/deepwave/base
  copying deepwave/base/extract.py -> build/lib.linux-x86_64-3.9/deepwave/base
  copying deepwave/base/model.py -> build/lib.linux-x86_64-3.9/deepwave/base
  copying deepwave/base/pad.py -> build/lib.linux-x86_64-3.9/deepwave/base
  copying deepwave/base/propagator.py -> build/lib.linux-x86_64-3.9/deepwave/base
  creating build/lib.linux-x86_64-3.9/deepwave/scalar
  copying deepwave/scalar/__init__.py -> build/lib.linux-x86_64-3.9/deepwave/scalar
  copying deepwave/scalar/scalar.py -> build/lib.linux-x86_64-3.9/deepwave/scalar
  copying deepwave/scalar/scalar_born.py -> build/lib.linux-x86_64-3.9/deepwave/scalar
  running build_ext
  building 'scalar1d_cpu_iso_4_float' extension
  creating build/temp.linux-x86_64-3.9
  creating build/temp.linux-x86_64-3.9/deepwave
  creating build/temp.linux-x86_64-3.9/deepwave/scalar
  /ibex/scratch/izzatum/pytorch_project/env/bin/x86_64-conda-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /ibex/scratch/izzatum/pytorch_project/env/include -I/ibex/scratch/izzatum/pytorch_project/env/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /ibex/scratch/izzatum/pytorch_project/env/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /ibex/scratch/izzatum/pytorch_project/env/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /ibex/scratch/izzatum/pytorch_project/env/include -fPIC -DDIM=1 -DTYPE=float -Ideepwave/scalar -I/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include -I/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/TH -I/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/THC -I/ibex/scratch/izzatum/pytorch_project/env/include/python3.9 -c deepwave/scalar/scalar.cpp -o build/temp.linux-x86_64-3.9/deepwave/scalar/scalar.o -Ofast -march=native -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=scalar1d_cpu_iso_4_float -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
  /ibex/scratch/izzatum/pytorch_project/env/bin/x86_64-conda-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /ibex/scratch/izzatum/pytorch_project/env/include -I/ibex/scratch/izzatum/pytorch_project/env/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /ibex/scratch/izzatum/pytorch_project/env/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /ibex/scratch/izzatum/pytorch_project/env/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /ibex/scratch/izzatum/pytorch_project/env/include -fPIC -DDIM=1 -DTYPE=float -Ideepwave/scalar -I/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include -I/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/TH -I/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/THC -I/ibex/scratch/izzatum/pytorch_project/env/include/python3.9 -c deepwave/scalar/scalar_cpu.cpp -o build/temp.linux-x86_64-3.9/deepwave/scalar/scalar_cpu.o -Ofast -march=native -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=scalar1d_cpu_iso_4_float -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
  /ibex/scratch/izzatum/pytorch_project/env/bin/x86_64-conda-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /ibex/scratch/izzatum/pytorch_project/env/include -I/ibex/scratch/izzatum/pytorch_project/env/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /ibex/scratch/izzatum/pytorch_project/env/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /ibex/scratch/izzatum/pytorch_project/env/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /ibex/scratch/izzatum/pytorch_project/env/include -fPIC -DDIM=1 -DTYPE=float -Ideepwave/scalar -I/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include -I/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/TH -I/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/THC -I/ibex/scratch/izzatum/pytorch_project/env/include/python3.9 -c deepwave/scalar/scalar_wrapper.cpp -o build/temp.linux-x86_64-3.9/deepwave/scalar/scalar_wrapper.o -Ofast -march=native -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=scalar1d_cpu_iso_4_float -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
  <command-line>: error: expected '>' before numeric constant
  /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/ATen/NativeMetaFunctions.h:34:32: note: in expansion of macro 'DIM'
     34 |                 template <bool DIM = false>
        |                                ^~~
  In file included from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/ATen/NativeFunctions.h:6,
                   from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/ATen/TensorIndexing.h:11,
                   from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/ATen/ATen.h:20,
                   from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                   from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                   from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                   from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                   from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                   from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                   from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                   from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/extension.h:4,
                   from deepwave/scalar/scalar_wrapper.cpp:1:
  /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/ATen/NativeMetaFunctions.h: In member function 'at::meta::structured_all_dim::precompute_out<true> at::meta::structured_all_dim::precompute_out<<anonymous> >::set_dim(int64_t)':
  /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/ATen/NativeMetaFunctions.h:38:43: error: static assertion failed: dim already set
     38 |                         static_assert(DIM == false, "dim already set");
  /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/ATen/NativeMetaFunctions.h: At global scope:
  <command-line>: error: expected '>' before numeric constant
  /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/ATen/NativeMetaFunctions.h:51:32: note: in expansion of macro 'DIM'
     51 |                 template <bool DIM = false>
        |                                ^~~
  In file included from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/ATen/NativeFunctions.h:6,
                   from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/ATen/TensorIndexing.h:11,
                   from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/ATen/ATen.h:20,
                   from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                   from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                   from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                   from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                   from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                   from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                   from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                   from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/extension.h:4,
                   from deepwave/scalar/scalar_wrapper.cpp:1:
  /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/ATen/NativeMetaFunctions.h: In member function 'at::meta::structured_any_dim::precompute_out<true> at::meta::structured_any_dim::precompute_out<<anonymous> >::set_dim(int64_t)':
  /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/ATen/NativeMetaFunctions.h:55:43: error: static assertion failed: dim already set
     55 |                         static_assert(DIM == false, "dim already set");
  error: command '/ibex/scratch/izzatum/pytorch_project/env/bin/x86_64-conda-linux-gnu-cc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for deepwave
  Running setup.py clean for deepwave
Failed to build deepwave
Installing collected packages: deepwave
    Running setup.py install for deepwave ... error
    ERROR: Command errored out with exit status 1:
     command: /ibex/scratch/izzatum/pytorch_project/env/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4dd_7iq8/deepwave_8660e702ae784fbdb012b4e28101f5f6/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4dd_7iq8/deepwave_8660e702ae784fbdb012b4e28101f5f6/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-7wgksrsr/install-record.txt --single-version-externally-managed --compile --install-headers /ibex/scratch/izzatum/pytorch_project/env/include/python3.9/deepwave
         cwd: /tmp/pip-install-4dd_7iq8/deepwave_8660e702ae784fbdb012b4e28101f5f6/
    Complete output (70 lines):
    Warning: 'classifiers' should be a list, got type 'tuple'
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.9
    creating build/lib.linux-x86_64-3.9/deepwave
    copying deepwave/__init__.py -> build/lib.linux-x86_64-3.9/deepwave
    copying deepwave/utils.py -> build/lib.linux-x86_64-3.9/deepwave
    copying deepwave/wavelets.py -> build/lib.linux-x86_64-3.9/deepwave
    creating build/lib.linux-x86_64-3.9/deepwave/base
    copying deepwave/base/__init__.py -> build/lib.linux-x86_64-3.9/deepwave/base
    copying deepwave/base/extract.py -> build/lib.linux-x86_64-3.9/deepwave/base
    copying deepwave/base/model.py -> build/lib.linux-x86_64-3.9/deepwave/base
    copying deepwave/base/pad.py -> build/lib.linux-x86_64-3.9/deepwave/base
    copying deepwave/base/propagator.py -> build/lib.linux-x86_64-3.9/deepwave/base
    creating build/lib.linux-x86_64-3.9/deepwave/scalar
    copying deepwave/scalar/__init__.py -> build/lib.linux-x86_64-3.9/deepwave/scalar
    copying deepwave/scalar/scalar.py -> build/lib.linux-x86_64-3.9/deepwave/scalar
    copying deepwave/scalar/scalar_born.py -> build/lib.linux-x86_64-3.9/deepwave/scalar
    running build_ext
    /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/utils/cpp_extension.py:381: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
      warnings.warn(msg.format('we could not find ninja.'))
    building 'scalar1d_cpu_iso_4_float' extension
    creating build/temp.linux-x86_64-3.9
    creating build/temp.linux-x86_64-3.9/deepwave
    creating build/temp.linux-x86_64-3.9/deepwave/scalar
    /ibex/scratch/izzatum/pytorch_project/env/bin/x86_64-conda-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /ibex/scratch/izzatum/pytorch_project/env/include -I/ibex/scratch/izzatum/pytorch_project/env/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /ibex/scratch/izzatum/pytorch_project/env/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /ibex/scratch/izzatum/pytorch_project/env/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /ibex/scratch/izzatum/pytorch_project/env/include -fPIC -DDIM=1 -DTYPE=float -Ideepwave/scalar -I/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include -I/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/TH -I/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/THC -I/ibex/scratch/izzatum/pytorch_project/env/include/python3.9 -c deepwave/scalar/scalar.cpp -o build/temp.linux-x86_64-3.9/deepwave/scalar/scalar.o -Ofast -march=native -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=scalar1d_cpu_iso_4_float -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    /ibex/scratch/izzatum/pytorch_project/env/bin/x86_64-conda-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /ibex/scratch/izzatum/pytorch_project/env/include -I/ibex/scratch/izzatum/pytorch_project/env/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /ibex/scratch/izzatum/pytorch_project/env/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /ibex/scratch/izzatum/pytorch_project/env/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /ibex/scratch/izzatum/pytorch_project/env/include -fPIC -DDIM=1 -DTYPE=float -Ideepwave/scalar -I/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include -I/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/TH -I/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/THC -I/ibex/scratch/izzatum/pytorch_project/env/include/python3.9 -c deepwave/scalar/scalar_cpu.cpp -o build/temp.linux-x86_64-3.9/deepwave/scalar/scalar_cpu.o -Ofast -march=native -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=scalar1d_cpu_iso_4_float -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    /ibex/scratch/izzatum/pytorch_project/env/bin/x86_64-conda-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /ibex/scratch/izzatum/pytorch_project/env/include -I/ibex/scratch/izzatum/pytorch_project/env/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /ibex/scratch/izzatum/pytorch_project/env/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /ibex/scratch/izzatum/pytorch_project/env/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /ibex/scratch/izzatum/pytorch_project/env/include -fPIC -DDIM=1 -DTYPE=float -Ideepwave/scalar -I/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include -I/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/TH -I/ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/THC -I/ibex/scratch/izzatum/pytorch_project/env/include/python3.9 -c deepwave/scalar/scalar_wrapper.cpp -o build/temp.linux-x86_64-3.9/deepwave/scalar/scalar_wrapper.o -Ofast -march=native -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=scalar1d_cpu_iso_4_float -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    <command-line>: error: expected '>' before numeric constant
    /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/ATen/NativeMetaFunctions.h:34:32: note: in expansion of macro 'DIM'
       34 |                 template <bool DIM = false>
          |                                ^~~
    In file included from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/ATen/NativeFunctions.h:6,
                     from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/ATen/TensorIndexing.h:11,
                     from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/ATen/ATen.h:20,
                     from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                     from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                     from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                     from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                     from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                     from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                     from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                     from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/extension.h:4,
                     from deepwave/scalar/scalar_wrapper.cpp:1:
    /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/ATen/NativeMetaFunctions.h: In member function 'at::meta::structured_all_dim::precompute_out<true> at::meta::structured_all_dim::precompute_out<<anonymous> >::set_dim(int64_t)':
    /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/ATen/NativeMetaFunctions.h:38:43: error: static assertion failed: dim already set
       38 |                         static_assert(DIM == false, "dim already set");
    /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/ATen/NativeMetaFunctions.h: At global scope:
    <command-line>: error: expected '>' before numeric constant
    /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/ATen/NativeMetaFunctions.h:51:32: note: in expansion of macro 'DIM'
       51 |                 template <bool DIM = false>
          |                                ^~~
    In file included from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/ATen/NativeFunctions.h:6,
                     from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/ATen/TensorIndexing.h:11,
                     from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/ATen/ATen.h:20,
                     from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                     from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                     from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                     from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                     from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                     from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                     from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                     from /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/torch/extension.h:4,
                     from deepwave/scalar/scalar_wrapper.cpp:1:
    /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/ATen/NativeMetaFunctions.h: In member function 'at::meta::structured_any_dim::precompute_out<true> at::meta::structured_any_dim::precompute_out<<anonymous> >::set_dim(int64_t)':
    /ibex/scratch/izzatum/pytorch_project/env/lib/python3.9/site-packages/torch/include/ATen/NativeMetaFunctions.h:55:43: error: static assertion failed: dim already set
       55 |                         static_assert(DIM == false, "dim already set");
    error: command '/ibex/scratch/izzatum/pytorch_project/env/bin/x86_64-conda-linux-gnu-cc' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /ibex/scratch/izzatum/pytorch_project/env/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4dd_7iq8/deepwave_8660e702ae784fbdb012b4e28101f5f6/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4dd_7iq8/deepwave_8660e702ae784fbdb012b4e28101f5f6/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-7wgksrsr/install-record.txt --single-version-externally-managed --compile --install-headers /ibex/scratch/izzatum/pytorch_project/env/include/python3.9/deepwave Check the logs for full command output.

**Comment by pplotn** [comment]
Hello everyone,
Installation of gpu version of deepwave on ibex is possible. There is my experience on link below.
https://github.com/pplotn/deepwave/blob/master/installation_gpu_cluster

**Comment by ar4** [comment]
Hello Pavel,

Thank you for sharing your experience. I am glad that the process looks pretty clean and easy.

I am currently working on the next release of Deepwave. It is a complete re-write, but I hope that your installation script will still work.

**Comment by pplotn** [comment]
As for me the problem was that deepwave does not see some libraries like nvcc in conda provided cudatoolkit. So thats why using properly installed cuda with module load helps the deepwave installer to find necessary destinations.

**Comment by ar4** [comment]
The new 0.0.10 version of Deepwave that I mentioned has been released. I hope that installation might cause problems for slightly fewer users, but we shall have to wait and see. I'll close this issue for now, but please feel free to reopen it or create a new one if you encounter problems.
