### ISSUE TITLE
AttributeError: module 'deepwave' has no attribute 'wavelets'

### ISSUE THREAD

**Issue by Minorway** [ar4/deepwave#40]
dear sir:
is this problem due to that i used lastest pytorch version?

**Comment by ar4** [comment]
Dear Minorway,

Thank you for reporting the issue that you encountered. New versions of PyTorch do sometimes cause problems. I have just updated to the most recent version (1.10.1) and Deepwave still worked on the test that I ran. Do you have an example code that causes this error?

**Comment by Minorway** [comment]
> Dear Minorway,
> 
> Thank you for reporting the issue that you encountered. New versions of PyTorch do sometimes cause problems. I have just updated to the most recent version (1.10.1) and Deepwave still worked on the test that I ran. Do you have an example code that causes this error?

Woo, so happy! I have solved this issue. I found that there were no deepwave packages available under pytorch with cuda. The only one can be installed was without wavelets.py etc . When I created a new environment(pytorch-cpu), it works.

**Comment by ar4** [comment]
That's great news, and I'm happy that you are happy. But does this mean that you have a CUDA-capable GPU but are not able to use Deepwave on it? It is much faster on a GPU, so it is worth the effort of trying to get it to work. I only tested with the new PyTorch version on a CPU so far. I will test it now on a GPU to see if I encounter a problem.

**Comment by ar4** [comment]
I installed and tested Deepwave on a Colaboratory GPU instance (with PyTorch 1.10) and it also ran without errors, so hopefully what you experienced is not a widespread problem. Do you wish to continue trying to diagnose the problem, or are you happy with your current Deepwave installation?
