### ISSUE TITLE
Installation error with cuda

### ISSUE THREAD

**Issue by Kelen-LYC** [ar4/deepwave#42]
Hi Alan, thanks for your deepwave.
Deepwave-cpu works well for me. But when I install deepwave with cuda on my windows, it returns an error. Looking for your help.
Here is the report from pip.

```
 "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\nvcc" -c deepwave\scalar\scalar_gpu.cu -o build\temp.win-amd64-3.7\Release\deepwave\scalar\scalar_gpu.obj -Ideepwave\scalar -ID:\Miniconda3\envs\deepwave\lib\site-packages\torch\include -ID:\Miniconda3\envs\deepwave\lib\site-packages\torch\include\torch\csrc\api\include -ID:\Miniconda3\envs\deepwave\lib\site-packages\torch\include\TH -ID:\Miniconda3\envs\deepwave\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\include" -ID:\Miniconda3\envs\deepwave\include -ID:\Miniconda3\envs\deepwave\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe--diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__-D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --restrict -O3 --use_fast_math -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=scalar1d_gpu_iso_4_float -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_8
6,code=sm_86 --use-local-env
```
      
**C:\Users\dell\AppData\Local\Temp\pip-install-hyawlsyh\deepwave_c21d48d98eb94f2487b9e27bb82533bf\deepwave\scalar\scalar.h(203): fatal error C1189: #error:  "Must specify the dimension, e.g. -D DEEPWAVE_DIM=1"
      scalar_gpu.cu
      error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.6\\bin\\nvcc.exe' failed with exit code 2
      [end of output]**

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> deepwave

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by Kelen-LYC** [comment]
> 

Thanks for reply, Alan. I can wait it.  The problem  just occers on  my Windows.  Sometimes I use Google's colab and deepwave-gpu works well there.  I guess there are some different rules of cuda between Colab (Linux) and Windows.  I haven't test it on my linux laptop. Laptops have lower computing performance, you know. 

You are doing a greatful work. Waiting for your new deepwave.

**Comment by Kelen-LYC** [comment]
Today I can determine the problem is caused by windows. I just installed deepwave-gpu on arch and it installed successfully immediately.

**Comment by ar4** [comment]
That's good news! Hopefully the next release will work just as easily
on Windows.

**Comment by ar4** [comment]
Hello again,

It took longer than expected to release the new version. After much experimentation, I unfortunately decided that the TorchScript implementation that I hoped to use, which would have avoided the necessity for users to compile code and so would have avoided many problems such as those that you experienced on Windows, was not fast enough. The new version thus still uses C++/CUDA and so needs to be compiled. I changed the installation method slightly, so it might cause fewer problems, but I expect that it is probably still easiest to use it with Linux. I'm sorry that I don't have better news.
