### ISSUE TITLE
ModuleNotFoundError: No module named 'deepwave'

### ISSUE THREAD

**Issue by naveenguptaiitr** [ar4/deepwave#53]
Hi Alan,

I am trying to import deepwave in a newly created conda virtual environment. I was able to install it successfully, however, when I try to import it, it says deepwave module not found. I can see that the package is installed inside the lib directory of the python that I am using, but, still it is unable to import it.
<img width="810" alt="Screen Shot 2023-03-15 at 12 28 59 PM" src="https://user-images.githubusercontent.com/59062374/225377222-a57c1c6b-bf5d-4e8d-8240-1918055e63f5.png">

Could you please provide any advise in this situation?

**Comment by ar4** [comment]
To make sure that the Python you are running is the one from the
environment you think it is, you could try running `python -c "import
os; print(os.environ['CONDA_PREFIX'])"` and checking that it prints
the path that you expect. It might also be best to run the above pip
command with `python -m pip list` to again make sure it is the right
pip that runs.

**Comment by wuguoning** [comment]
Dear Alan,
1. I has installed deepwave "pip install deepwave"
2. But has the errors below:
Traceback (most recent call last):
  File "/home/gordon/Projects/deepwave/examples/ex1.py", line 56, in <module>
    out = dpscalar(v, dx, dt, source_amplitudes=source_amplitudes,
TypeError: 'module' object is not callable

could you help me about this. Thanks!
