### ISSUE TITLE
scalar_born memory issue

### ISSUE THREAD

**Issue by acse-wz19** [ar4/deepwave#60]
Hi Alan,

I install deepwave in my machine, and every other functions work well except function scalar_born. When I update the two models  after a few iterations, it comes out this error: 
GPUassert: an illegal memory access was encountered /home/weilin/miniconda3/lib/python3.10/site-packages/deepwave/scalar_born.cu 1033

Do you have any idea of this issue?
I am looking forward to your reply.
Best,
Weilin

**Comment by ar4** [comment]
Hi Weilin,

It is nice to hear from you again. I apologise for the delay in replying -
I have been travelling internationally and didn't check my email. I have
just returned and so will look into this issue in the morning. I am sorry
that you encountered it, and thank you for reporting it.Message ID:
***@***.***>

>

**Comment by acse-wz19** [comment]
Hi Alan,

I have figured out the problem. This is simply because one of my GPUs is out of work.

Hope you have a wonderful traveling experience!

Best,
Weilin

发送自 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Alan Richardson ***@***.***>
发送时间: Wednesday, July 12, 2023 11:34:11 PM
收件人: ar4/deepwave ***@***.***>
抄送: Zhang, Weilin ***@***.***>; Author ***@***.***>
主题: Re: [ar4/deepwave] scalar_born memory issue (Issue #60)


This email from ***@***.*** originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



Hi Weilin,

It is nice to hear from you again. I apologise for the delay in replying -
I have been travelling internationally and didn't check my email. I have
just returned and so will look into this issue in the morning. I am sorry
that you encountered it, and thank you for reporting it.Message ID:
***@***.***>

>

―

**Comment by ar4** [comment]
I am very glad to hear that you solved it.

**Comment by acse-wz19** [comment]
Thanks a lot.

Best，
Weilin

发送自 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Alan Richardson ***@***.***>
发送时间: Thursday, July 13, 2023 9:57:50 AM
收件人: ar4/deepwave ***@***.***>
抄送: Zhang, Weilin ***@***.***>; Author ***@***.***>
主题: Re: [ar4/deepwave] scalar_born memory issue (Issue #60)


This email from ***@***.*** originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



Closed #60<https://github.com/ar4/deepwave/issues/60> as completed.

―
