### ISSUE TITLE
Generate the waveform data

### ISSUE THREAD

**Issue by ywsslr** [ar4/deepwave#67]
Hello,
I recently use the deepwave and it becomes my favorite simulation package. And I want to ask if I can change a little source code of deepwave to generate the entire waveform data (shape of nt*nx*nz). I also want to know will the deepwave have the plan to support the 3D simulation in the future?

**Comment by ywsslr** [comment]
Thank you for answering my question and I have solved the problem by the first method easily. And I will try  the other methods when I am free because I think the first method is enough for my problem. I will ask you when I have other problems to use deepwave. I sincerely hope the deepwave better and better and I will continue to monitor it. Thanks.

**Comment by ar4** [comment]
I am glad to hear that the easy solution was enough to solve your problem. I am going to close this Issue now, but please feel free to reopen it if you need to.
