### ISSUE TITLE
Is it possible to obtain cross correlation sensitivity kernel for RTM using p-wave excitation source and S-wave excitation source?

### ISSUE THREAD

**Issue by makeabhishek** [ar4/deepwave#84]
Hi Alan, 
I hope you are doing good. 

I want to perform cross correlation sensitivity kernel analysis in RTM. What is the best way to perform that?

**Comment by ar4** [comment]
Do you mean that you wish to calculate the gradient/sensitivity kernel of a
cross-correlation loss function? If so, then I suggest calculating the
cross-correlation loss function, calling .backward() on it, and looking at
the .grad attribute of the model.

**Comment by makeabhishek** [comment]
I'm a little confuse. Why there would be a loss function in RTM? 
Will it not be direct cross correlation of forward and backward wavefield?

**Comment by makeabhishek** [comment]
I'm looking something like the below image from the reference "[Elastic reflection waveform inversion based on the decomposition of sensitivity kernels](https://library.seg.org/doi/epub/10.1190/geo2018-0220.1)"
![image](https://github.com/user-attachments/assets/85e0e19d-f4cc-40f8-937a-0a9d601b4e27)

I think something like that is mentioned at deepwave website https://ausargeo.com/deepwave/example_large_edge_gradient.

Need to consider P-wave and S-wave excitation sources.

**Comment by ar4** [comment]
Thank you for clarifying what you wish to calculate. The images show
gradients/sensitivity kernels. Gradients/sensitivity kernels are calculated
in the way that I described. However, I think the gradients/sensitivity
kernels in the paper that you linked to involve performing elastic LSRTM
using an elastic Born propagator. Deepwave does not have an elastic Born
propagator, and so it is probably not possible to produce those particular
images with Deepwave.

**Comment by makeabhishek** [comment]
Thanks @ar4 for the guidance. Is it possible to do it using LSRTM? Does LSRTM has elastic propagation?

**Comment by ar4** [comment]
LSRTM requires a Born propagator. Deepwave only has a scalar wave equation
Born propagator, not an elastic one. It is therefore probably not possible
to implement the method described in the paper that you referred to with
Deepwave.
